# Generated by Django 5.0.2 on 2024-02-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_profile',
            new_name='author',
        ),
    ]
